# Generated by Django 5.2.6 on 2025-12-10 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FichaMedica',
            fields=[
                ('id_ficha', models.BigAutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=120)),
                ('notas', models.TextField(blank=True, null=True)),
                ('hora_ficha', models.DateTimeField(blank=True, null=True)),
                ('direccion_paciente', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono_paciente', models.CharField(blank=True, max_length=15, null=True)),
                ('rut_paciente', models.CharField(blank=True, max_length=15, null=True)),
                ('nombre_paciente', models.CharField(blank=True, max_length=50, null=True)),
                ('apellido_paciente', models.CharField(blank=True, max_length=50, null=True)),
                ('prevision_paciente', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HoraAgendada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_final', models.TimeField()),
                ('paciente', models.CharField(max_length=50)),
                ('estado', models.CharField(choices=[('reservada', 'Reservada'), ('cancelada', 'Cancelada'), ('completada', 'Completada')], default='reservada', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id_paciente', models.BigAutoField(primary_key=True, serialize=False)),
                ('rut', models.CharField(max_length=15, unique=True, verbose_name='RUT')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=50, verbose_name='Apellido')),
                ('email', models.EmailField(max_length=100, verbose_name='Correo electrónico')),
                ('direccion', models.CharField(max_length=150, verbose_name='Dirección')),
                ('telefono', models.CharField(max_length=15, verbose_name='Teléfono')),
                ('prevision', models.CharField(max_length=100, verbose_name='Previsión')),
                ('usuarios_id_usuario', models.BigIntegerField(blank=True, null=True, verbose_name='ID de usuario asociado')),
            ],
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Secretaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut_secretaria', models.CharField(max_length=15, unique=True)),
                ('nombre_secretaria', models.CharField(max_length=50)),
                ('apellido_secretaria', models.CharField(max_length=50)),
                ('email_secretaria', models.EmailField(max_length=100, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('usuarios_id_usuario', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
    ]
