# Generated by Django 5.2.6 on 2025-12-12 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut_doctor', models.CharField(max_length=15, unique=True)),
                ('nombre_doctor', models.CharField(max_length=50)),
                ('apellido_doctor', models.CharField(max_length=50)),
                ('email_doctor', models.EmailField(max_length=100, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('usuarios_id_usuario', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
    ]
