# Generated by Django 5.2.6 on 2025-12-12 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_doctor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registro',
            old_name='password_hash',
            new_name='password',
        ),
    ]
